# Generated by Django 5.2.17 on 2026-10-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LandingBanner',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Landing Banner',
                'verbose_name_plural': 'Landing Banner',
            },
        ),
        migrations.CreateModel(
            name='LandingForWhomSection',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Landing For Whom',
                'verbose_name_plural': 'Landing For Whom',
            },
        ),
        migrations.CreateModel(
            name='LandingHero',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Landing Hero',
                'verbose_name_plural': 'Landing Hero',
            },
        ),
        migrations.CreateModel(
            name='LandingWhyWorthSection',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Landing Why Worth',
                'verbose_name_plural': 'Landing Why Worth',
            },
        ),
        migrations.CreateModel(
            name='LandingForWhomCard',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cards',
                        to='content_sections.landingforwhomsection',
                    ),
                ),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingHeroImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                (
                    'hero',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='content_sections.landinghero',
                    ),
                ),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingWhyWorthItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                (
                    'section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='content_sections.landingwhyworthsection',
                    ),
                ),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
