# Generated by Django 5.2.17 on 2026-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=255)),
                (
                    'edrpou_or_ipn',
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ('investor_description', models.TextField(blank=True)),
                ('investor_phone', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                (
                    'investor_type',
                    models.CharField(
                        choices=[
                            ('private', 'Приватна особа'),
                            ('fund', 'Фонд'),
                            ('company', 'Компанія'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'investment_min',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
        ),
    ]
