# Generated by Django 5.2.17 on 2026-10-06 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='investor_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='investorprofile',
            index=models.Index(fields=['investor_type'], name='investor_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='investorprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('investment_min__isnull', True),
                    ('investment_min__gte', 0),
                    _connector='OR',
                ),
                name='investor_investment_min_non_negative',
            ),
        ),
    ]
