# Generated by Django 5.2.17 on 2026-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='investor_type',
            field=models.CharField(choices=[('private', 'Приватна особа'), ('fund', 'Фонд'), ('company', 'Компанія')], max_length=20),
        ),
    ]
