# Generated by Django 5.2.17 on 2026-10-03 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_alter_investorprofile_investor_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='investorprofile',
            index=models.Index(fields=['investor_type'], name='investor_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='investorprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('investment_min__isnull', True),
                    ('investment_min__gte', 0),
                    _connector='OR',
                ),
                name='investor_investment_min_non_negative',
            ),
        ),
    ]
