[pytest]
DJANGO_SETTINGS_MODULE = config.settings
testpaths = .
python_files = test_*.py *_test.py tests.py
addopts = -ra --strict-markers
markers =
    models: model tests
    api: HTTP endpoint tests
