# Generated by Django 5.2.17 on 2026-10-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='startups.startupprofile'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_stage'], name='project_stage_idx'),
        ),
    ]
