# Generated by Django 5.2.17 on 2026-10-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='startup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='projects',
                to='startups.startupprofile',
            ),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_stage'], name='project_stage_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(
                condition=models.Q(('investment_sum__gt', 0)),
                name='project_investment_sum_gt_zero',
            ),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(
                condition=models.Q(('raised_amount__gte', 0)),
                name='project_raised_amount_gte_zero',
            ),
        ),
    ]
