# Generated by Django 5.2.17 on 2026-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('startups', '0004_startupprofile_startup_employees_gte_one'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(
                condition=models.Q(('investment_sum__gt', 0)),
                name='project_investment_sum_gt_zero',
            ),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(
                condition=models.Q(('raised_amount__gte', 0)),
                name='project_raised_amount_gte_zero',
            ),
        ),
    ]
