# Generated by Django 5.2.17 on 2026-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('startup_id', models.AutoField(primary_key=True, serialize=False)),
                ('startup_name', models.CharField(max_length=255)),
                (
                    'edrpou_or_ipn',
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ('startup_description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('startup_phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                (
                    'industry',
                    models.CharField(
                        choices=[
                            ('it', 'Інформаційні технології / IT'),
                            ('finance', 'Фінанси та FinTech'),
                            ('healthcare', "Медицина та охорона здоров'я"),
                            ('education', 'Освіта'),
                            ('agriculture', 'Сільське господарство'),
                            ('e_commerce', 'Електронна торгівля'),
                            ('green_energy', 'Зелена енергетика / Екологія'),
                            ('food', 'Їжа / Харчова промисловість'),
                            ('beverages', 'Напої'),
                            ('packaging', 'Пакування та тара'),
                            ('catering', 'Кейтеринг / Ресторанний бізнес'),
                            ('winemaking', 'Виноробство'),
                            ('other', 'Інше'),
                        ],
                        default='other',
                        max_length=100,
                    ),
                ),
                ('founded_at', models.DateField(blank=True, null=True)),
                ('employees', models.IntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
