# Generated by Django 5.2.17 on 2026-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('startup_id', models.AutoField(primary_key=True, serialize=False)),
                ('startup_name', models.CharField(max_length=255)),
                ('edrpou_or_ipn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('startup_description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('startup_phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('industry', models.CharField(max_length=100)),
                ('founded_at', models.DateField(blank=True, null=True)),
                ('employees', models.IntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
