# Generated by Django 5.2.17 on 2026-10-06 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='startup_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(fields=['industry'], name='startup_industry_idx'),
        ),
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(('employees__gte', 1)),
                name='startup_employees_gte_one',
            ),
        ),
    ]
