# Generated by Django 5.2.17 on 2026-10-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='industry',
            field=models.CharField(choices=[('it', 'Інформаційні технології / IT'), ('finance', 'Фінанси та FinTech'), ('healthcare', "Медицина та охорона здоров'я"), ('education', 'Освіта'), ('agriculture', 'Сільське господарство'), ('e_commerce', 'Електронна торгівля'), ('green_energy', 'Зелена енергетика / Екологія'), ('food', 'Їжа / Харчова промисловість'), ('beverages', 'Напої'), ('packaging', 'Пакування та тара'), ('catering', 'Кейтеринг / Ресторанний бізнес'), ('winemaking', 'Виноробство'), ('other', 'Інше')], default='other', max_length=100),
        ),
    ]
