# Generated by Django 5.2.17 on 2026-10-03 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_startupprofile_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='startupprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(('employees__gte', 1)),
                name='startup_employees_gte_one',
            ),
        ),
    ]
