# Generated by Django 5.2.17 on 2026-10-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startupprofile_startup_employees_gte_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('industry_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['industry_name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='startupprofile',
            name='startup_industry_idx',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='industry',
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='startup_profiles', to='startups.industry'),
        ),
    ]
