# Generated by Django 5.2.17 on 2026-10-04 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_populate_industries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='location',
            field=models.CharField(choices=[('chernivtsi', 'Чернівецька область'), ('cherkasy', 'Черкаська область'), ('chernihiv', 'Чернігівська область'), ('dnipro', 'Дніпропетровська область'), ('donetsk', 'Донецька область'), ('ivano_frankivsk', 'Івано-Франківська область'), ('kharkiv', 'Харківська область'), ('kherson', 'Херсонська область'), ('khmelnytskyi', 'Хмельницька область'), ('kyiv_city', 'м. Київ'), ('kyiv', 'Київська область'), ('kirovohrad', 'Кіровоградська область'), ('luhansk', 'Луганська область'), ('lviv', 'Львівська область'), ('mykolaiv', 'Миколаївська область'), ('odesa', 'Одеська область'), ('poltava', 'Полтавська область'), ('rivne', 'Рівненська область'), ('sumy', 'Сумська область'), ('ternopil', 'Тернопільська область'), ('vinnytsia', 'Вінницька область'), ('volyn', 'Волинська область'), ('zakarpattia', 'Закарпатська область'), ('zaporizhzhia', 'Запорізька область'), ('zhytomyr', 'Житомирська область'), ('crimea', 'Автономна Республіка Крим')], default='kyiv_city', max_length=50),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='industries',
            field=models.ManyToManyField(related_name='startup_profiles', to='startups.industry'),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(fields=['location'], name='startup_location_idx'),
        ),
    ]
