# Generated by Django 5.2.17 on 2026-10-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_remove_startupprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='thumbs/'),
        ),
    ]
