# Generated by Django 5.2.17 on 2026-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SavedProject',
            fields=[
                (
                    'saved_project_id',
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
