# Generated by Django 5.2.17 on 2026-10-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproject',
            name='investor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='saved_projects',
                to='investors.investorprofile',
            ),
        ),
    ]
