# Generated by Django 5.2.17 on 2026-10-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='saved_by_investors', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='savedproject',
            unique_together={('investor', 'project')},
        ),
    ]
