# Generated by Django 5.2.17 on 2026-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
        ('investors', '0004_investorprofile_investor_type_idx_and_more'),
        ('projects', '0003_project_project_investment_sum_gt_zero_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedproject',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='savedproject',
            constraint=models.UniqueConstraint(
                fields=('investor', 'project'), name='saved_project_unique'
            ),
        ),
    ]
