# Generated by Django 5.2.17 on 2026-10-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'show_hero',
                    models.BooleanField(default=True, verbose_name='Landing Hero'),
                ),
                (
                    'show_banner',
                    models.BooleanField(default=True, verbose_name='Landing Banner'),
                ),
                (
                    'show_for_whom',
                    models.BooleanField(default=True, verbose_name='Landing For Whom'),
                ),
                (
                    'show_why_worth',
                    models.BooleanField(default=True, verbose_name='Landing Why Worth'),
                ),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Page',
            },
        ),
    ]
