# Generated by Django 5.2.17 on 2026-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('startup', 'Стартап'), ('investor', 'Інвестор')], max_length=20),
        ),
    ]
