# Generated by Django 5.2.17 on 2026-10-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active_user_user_role_idx'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
